### ISSUE TITLE
All Cards - with pagination

### ISSUE THREAD

**Issue by katricz** [lionel-panhaleux/krcg-api#6]
Hey Lionel, 

First of all, Thank you for the excelent work.

I'm learning NextJS and MongoDB. Working at https://alamuthq.netlify.app/

Can we have an API (or update POST/card_search) that return a List of Cards with pagination? So I can get the 100 first cards, then the 101 to 200 ...

**Comment by lionel-panhaleux** [comment]
Hi @katricz , sorry for the late answer, I think we discussed it already but for the sake of traceability, let me answer here ^^.

I do not advise paginating cards queries. There are not many cards and the whole cards collection is held in memory on the server side. So querying all the cards should be pretty fast already. If you want to paginate on the UI end to avoid having to display thousands of cards at once, it might be faster / more reactive to do so in JS directly, don't you think?

Happy to change my mind if there are strong arguments the other way, nothing I set in stone.
